### ISSUE TITLE
can you share the server project?

### ISSUE THREAD

**Issue by h0ttz** [sibvic/trade_copier#1]
Hi, can you share the server project? I would like to self-host the server on my own machine instead need to use 'ProfitRobots.com' server as a transport layer.

**Comment by sibvic** [comment]
[As Windows App](https://drive.google.com/file/d/1RqLQqgbkopeRb4cB3dXc2oJ2c1x_DL8u/view?usp=sharing)
[As docker](https://drive.google.com/file/d/17mpcN4oDRLONFh-MefC8Gu_yhiTZuQmN/view?usp=sharing)
You can type any license key. It'll work till the end of the year
